// Library crate root for BMSecResearch.
//
// This file exists so the project can be built as both:
//   * A desktop binary (`src/main.rs` is the entry point and calls
//     `bmsecresearch_lib::run()`)
//   * An Android shared object (Tauri's mobile build packages the
//     `cdylib` target produced by this lib into the APK and calls
//     `bmsecresearch_lib::run()` via the JNI bridge generated by
//     `tauri::mobile_entry_point`)
//
// All Tauri Builder setup, command registration, and state management
// lives here so both entry points share the same code path. Desktop-
// only utilities (filesystem logging to the user's Desktop, CLI mode)
// stay in `main.rs` because they don't make sense on a phone.

mod app_paths;
mod binary;
mod calibration_read;
mod capture;
mod commands;
mod error;
mod hsfz;
mod op_log;
mod pcap;
mod proxy;
mod security;
mod simulator;
mod types;
mod uds;

use commands::{AppState, CaptureState};
use simulator::SimulatorState;
use std::sync::atomic::AtomicBool;
use std::sync::{Arc, Mutex};

// Re-exports so `main.rs` can use the offline-extract pipeline for the
// desktop CLI mode without needing private-module access.
pub use binary::assembler;
pub use hsfz::parser as hsfz_parser;
pub use pcap::reader as pcap_reader;
pub use pcap::tcp_reassembly;
pub use uds::session as uds_session;

/// Application entry point shared between desktop and mobile.
///
/// On desktop, this is called from `main.rs` after CLI-mode handling.
/// On mobile, the `#[cfg_attr(mobile, tauri::mobile_entry_point)]`
/// attribute makes Tauri's Android bridge invoke this function from
/// the JNI shim that the `tauri android build` toolchain generates.
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_process::init())
        .plugin(tauri_plugin_dialog::init())
        // plugin-fs is required for cross-platform file I/O. The frontend
        // uses its `writeFile` / `readFile` APIs to write user-picked
        // paths, because they handle Android Storage Access Framework
        // content URIs (`content://...`) transparently — `std::fs` does
        // not. See the file-I/O architecture comment in
        // `src-tauri/src/calibration_read/mod.rs`.
        .plugin(tauri_plugin_fs::init())
        // Resolve the platform-correct app data directory from Tauri's
        // path API and stash it in `app_paths::APP_DATA_DIR` so internal
        // callers (profile loaders, capture writer, etc.) can read it
        // without threading `AppHandle` through every function. On
        // Android this resolves to the app-scoped external storage
        // area which is visible to file managers without root.
        .setup(|app| {
            use tauri::Manager;
            let data_dir = app
                .path()
                .app_data_dir()
                .map_err(|e| format!("resolve app_data_dir: {}", e))?;
            app_paths::init(data_dir);
            Ok(())
        })
        .manage(AppState {
            last_block_data: Mutex::new(None),
            capture: Mutex::new(CaptureState {
                session: None,
                thread: None,
            }),
            last_capture: Mutex::new(None),
            cancel_flag: Arc::new(AtomicBool::new(false)),
            last_bytes: Mutex::new(None),
            last_op_log: Mutex::new(None),
        })
        .manage(SimulatorState::new())
        .manage(proxy::ProxyState::new())
        .invoke_handler(tauri::generate_handler![
            commands::extract_pcap,
            commands::save_binary,
            commands::pull_last_bytes,
            commands::pull_last_op_log,
            commands::cancel_active_operation,
            commands::get_platform,
            commands::has_live_capture,
            commands::list_interfaces,
            commands::start_capture,
            commands::stop_capture,
            commands::extract_captured_flash,
            commands::save_capture_pcap,
            commands::discard_capture,
            calibration_read::read_calibration_region,
            calibration_read::discovery::discover_vehicles,
            simulator::simulator_start,
            simulator::simulator_stop,
            simulator::simulator_status,
            simulator::simulator_list_profiles,
            simulator::simulator_get_profile,
            simulator::simulator_save_profile,
            simulator::simulator_delete_profile,
            simulator::simulator_create_empty_profile,
            simulator::simulator_get_dme_identifiers,
            simulator::simulator_set_dme_identifiers,
            simulator::simulator_import_ncd_backup,
            simulator::simulator_sample_ncd_backup,
            simulator::simulator_clone_from_car,
            simulator::simulator_captures_dir,
            simulator::simulator_list_flash_sessions,
            simulator::simulator_list_segments,
            simulator::simulator_export_flash_bin,
            proxy::proxy_start,
            proxy::proxy_stop,
            proxy::proxy_status,
            proxy::proxy_captures_dir,
            proxy::proxy_list_sessions,
            proxy::proxy_export_pcap,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
